
volumes:
  h2_data:
    driver: local
  valkey_data:
    driver: local

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    volumes:
      - h2_data:/opt/keycloak/data
      - ./target/keycloak-redis-0.1-SNAPSHOT-withdeps.jar:/opt/keycloak/providers/keycloak-redis-0.1-SNAPSHOT-withdeps.jar
    environment:
      KC_DB_USERNAME: "sa"
      KC_COMMUNITY_REDIS_CACHE_ENABLED: true
      KC_SPI_REDIS_CONNECTION_DEFAULT_MODE: "standalone"
      KC_SPI_REDIS_CONNECTION_DEFAULT_NODES: "valkey:6379"
      KC_CACHE: local
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO,org.keycloak.STACK_TRACE:TRACE,io.phasetwo.keycloak.redis:TRACE
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,address=*:8787,server=y,suspend=n -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    ports:
      - 8080:8080
      - 8787:8787
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--verbose"]
    depends_on:
      - valkey
  valkey:
    image: valkey/valkey:8.1.5
    ports:
      - "6379:6379"
    command: >
      valkey-server
      --appendonly yes
      --protected-mode no
    volumes:
      - valkey_data:/data
