volumes:
  cockroach_data:
    driver: local
  caddy_data:
    driver: local

services:
  cockroach:
    image: cockroachdb/cockroach:latest
    volumes:
      - cockroach_data:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
      - 26257:26257

  keycloak:
    image: quay.io/phasetwo/keycloak-crdb:26.7.1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      mode: replicated
      replicas: 3
    environment:
      KC_HTTP_PORT: 8080
      KC_DB: cockroach
      KC_TRANSACTION_XA_ENABLED: false
      KC_TRANSACTION_JTA_ENABLED: false
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB_URL_PROPERTIES: '?sslmode=disable&useCockroachMetadata=true'
      KC_DB_URL_HOST: cockroach
      KC_DB_URL_PORT: 26257
      KC_DB_URL_DATABASE: defaultdb
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: ''
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY_HEADERS: 'xforwarded'
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_CACHE: local
      KC_LOG_LEVEL: INFO
    entrypoint: /opt/keycloak/bin/kc.sh --verbose start
    depends_on:
      - cockroach

  caddy:
    image: caddy:2-alpine
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    depends_on:
      - keycloak
